default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: RunDiary_development
  host: db
  username: root
  password: password

test:
  <<: *default
  database: RunDiary_test
  host: db
  username: root
  password: password

production:
  <<: *default
  database: RunDiary_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost